version: '3.9'

services:
  backend-api:
    build:
      context: ./
      dockerfile: Dockerfile-Backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile-Frontend
    ports:
      - "4001:3000"
