FROM python:3 AS base

WORKDIR /usr/src/backend

COPY ./back-end/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./back-end/ .

################
# Debugger     #
################

FROM base as debugger

RUN pip install debugpy

ENTRYPOINT [ "python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "--wait-for-client", "./backend.py" ]

################
# Primary      #
################

FROM base as primary

ENTRYPOINT [ "python", "./backend.py"]